# Generated by Django 3.2.9 on 2021-11-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
    ]
